Домашнее задание №1
Frontend-Sirius-VK/2022-autumn-n.kuznetsov pull request #1
Opened 2022-11-26 07:27 UTC by Kuzy53

2022-11-26 16:35 UTC, Betchika99 requested changes
- [ ] т.к. проект - это уже папка, давай не будем плодить еще больше вложенностей и удалим папку MyProject
- [ ]  не выполнена первая часть условия ДЗ: _Оформить репозиторий и **структуру проекта с будущими компонентами (придерживаемся архитектуры MVC)**_

2022-11-26 16:35 UTC, Betchika99 commented on MyProject/index.html
> +    <h1>Hello World!</h1>
в рамках проекта вы должны показать знания в разработке СОВРЕМЕННОГО веб-приложение. это значит, что мы работаем со SPA, где такое недопустимо. можешь уже воспользоваться созданными папками и завести компонент для Hello World например (или для Main Page)

2022-11-26 16:35 UTC, Betchika99 commented on MyProject/package.json
> +    "start": "node Server.js"
обычно файлики js называют с маленькой буквы

2022-11-26 16:35 UTC, Betchika99 commented on MyProject/package.json
> +  "name": "myproject",
обычно name - это название репозитория. с кастомным названием может возникнуть проблема, если ты когда-нибудь захочешь опубликовать свой проект в NPM (открытую базу пакетов)

2022-11-26 16:35 UTC, Betchika99 commented on MyProject/package.json
> +  "author": "",
можно сюда записать себя, не надо стесняться :)

2022-11-29 22:17 UTC, Betchika99 commented on components/helloPage.js
> +export class helloPage {
классы обычно называем с заглавной буквы

2022-11-29 22:18 UTC, Betchika99 commented on components/helloPage.js
> +    elementAdd() {
такие методы обычно называют универсально - render (как в реакте)

2022-11-29 22:20 UTC, Betchika99 commented on index.js
> +const body = document.querySelector('body');
вообще лучше сделать пустой див на странице и его заполнять контентом. иначе у тебя будет проблема с тем, что скрипты будут всегда ПЕРЕД основной вёрсткой, а должны быть ПОСЛЕ (чтобы не блочить выполнение кода)

2022-11-29 22:20 UTC, Betchika99 requested changes
node modules должны быть в гитигноре(

2022-12-03 08:57 UTC, StealthTech requested changes

2022-12-03 08:57 UTC, StealthTech commented on index.html
> +        <script src="index.js" type="module"></script>
script вложен в div, так делать не стоит. с точки зрения вёрстки это не имеет смысла

2022-12-03 08:57 UTC, StealthTech commented on index.html
> +</html>
В конце текстовых файлов стоит всегда добавлять пустую строку https://semakin.dev/2020/05/no_newline_at_end_of_file/

2022-12-03 10:51 UTC, StealthTech approved these changes

2022-12-03 10:52 UTC, merged