Проектное ДЗ №2
Frontend-Sirius-VK/2022-autumn-n.kuznetsov pull request #2
Opened 2022-12-07 23:17 UTC by Kuzy53

2022-12-12 20:54 UTC, StealthTech requested changes
1. Приложи сюда комментарием скриншот, как выглядит твой проект в запущенном виде, пожалуйста. 
2. Не самая лучшая идея называть папку с картинками Image с большой буквы и класть в корень. Тогда лучше создать папку assets и в ней images, куда сложить картинки

2022-12-12 20:54 UTC, StealthTech commented on components/CardRecipe/CardRecipe.js
> +            recipeCard.render(recipe.url_image, recipe.name_recipe, recipe.category_recipe, recipe.time, recipe.description_recipe);
В языке JavaScript принято использовать camelCase, не snake_case

2022-12-12 20:54 UTC, StealthTech commented on components/CardRecipe/CardRecipe.js
> +}
В конце файла оставляем пустую строку https://semakin.dev/2020/05/no_newline_at_end_of_file/

2022-12-12 20:54 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +.descriptionEda_style {
Рекомендую использовать БЭМ: https://ru.bem.info/ (пока не обязательно)

2022-12-12 20:54 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.js
> +}
Рекомендую переписать на handlebars (пока не обязательно)

2022-12-12 20:54 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +    padding-right: 115px;
Почти никогда не стоит использовать размеры с не-круглыми значениями (115px НЕ ОК, 120px ОК). Это мешает дальнейшей вёрстке как правило. Можно так делать только с размерами картинок

2022-12-12 20:54 UTC, StealthTech commented on components/Header/Header.css
> +    -ms-flex-wrap: wrap;
Мы не требуем префиксы. Если ты сам дошел — это классно. Если откуда-то взял, то 

1. надо делать самостоятельно
2. писать префиксы не обязательно

2022-12-12 20:54 UTC, StealthTech commented on components/Header/Header.css
> +header {
Селекторы по тегу — антипаттерн. Давай сделаем по классу

2022-12-12 20:54 UTC, StealthTech commented on components/Header/Header.css
> +    color: rgb(0, 0, 0);
Цвета стоит выносить в палитру

2022-12-12 20:54 UTC, StealthTech commented on components/Header/Header.css
> +    color: rgb(175, 33, 43);
Все цвета в палитру

2022-12-12 20:54 UTC, StealthTech commented on components/Header/Header.css
> +color: rgb(0, 0, 0);
С отступами беда здесь и ниже

2022-12-12 20:54 UTC, StealthTech commented on main.css
> +@import "./components/RecipeCard/RecipeCard.css";
Либо одинарные, либо двойные кавычки. Я рекомендую одинарные

2022-12-12 20:54 UTC, StealthTech commented on models/RecipeData.js
> +    constructor(url_image = '', name_recipe = 'название рецепта', category_recipe = 'категория рецепта', time = 0, description_recipe = 'описание рецепта') {
camelCase

2022-12-12 20:54 UTC, StealthTech commented on server.js
>  app.get('/login', (req,res) => {
Можно выпилить, авторизация не требуется более

2022-12-15 15:59 UTC, Kuzy53 commented on components/CardRecipe/CardRecipe.js
> +            recipeCard.render(recipe.url_image, recipe.name_recipe, recipe.category_recipe, recipe.time, recipe.description_recipe);
![Снимок экрана от 2022-12-15 17-55-27](https://user-images.githubusercontent.com/91885270/207907931-c0ae6e6f-a9e0-4135-bd48-31b12454559a.png)

2022-12-15 22:24 UTC, StealthTech commented
<img width="667" alt="image" src="https://user-images.githubusercontent.com/5190765/207980128-ba022987-b664-4aec-94ea-023e845989d6.png">
Нажатие на "Рецепты" добавляет копию страницы в конце страницы

2022-12-15 22:25 UTC, StealthTech commented
Посреди страницы есть null 
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/5190765/207980217-d98fc547-d17a-465b-bc63-399f3272820b.png">

2022-12-15 22:27 UTC, StealthTech commented
Pull request должен называться "Домашнее задание №2"

2022-12-15 22:52 UTC, StealthTech requested changes
**Дедлайн: 17.12.22 23:59**
Требует исправлений

2022-12-15 22:52 UTC, StealthTech commented on components/Color/color.css
> +}
Не хватает пустой строки https://semakin.dev/2020/05/no_newline_at_end_of_file/

2022-12-15 22:52 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +    justify-content: center !important;
В лекции про специфичность упоминал, что !important избегаем всеми силами

2022-12-15 22:52 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +    min-width: 99.996%;
Это какой-то акробатический трюк. Давай придумаем способ его избежать

2022-12-15 22:52 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +    background-color: var(--description-color);;
;;

2022-12-15 22:52 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +    -moz-box-pack: center !important;
box-pack?

2022-12-15 22:52 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +}
Отступы

2022-12-15 22:52 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +    font: 15px / 36px PT Serif, Georgia, serif;
Воу. Давай разнесём этот шорткат на отдельные свойства

2022-12-15 22:52 UTC, StealthTech commented on components/DescriptionSiteEda/DescriptionSiteEda.js
> +        description.innerHTML += 'Ищите рецепты, выбирая категорию блюда, его подкатегорию, кухню или меню. А в дополнительных фильтрах можно искать по нужному (или ненужному) ингредиенту: просто нач
Такие тексты правильно выносить в константу вне классов

2022-12-15 22:52 UTC, StealthTech commented on components/Header/Header.css
> +header {
Не исправлено

2022-12-15 22:52 UTC, StealthTech commented on components/Header/Header.css
> +
Лишняя пустая строка

2022-12-15 22:52 UTC, StealthTech commented on components/Header/Header.css
> +
Лишняя пустая строка, отступы

2022-12-15 22:52 UTC, StealthTech commented on components/Header/Header.css
> +height: 60px;
Отступы

2022-12-15 22:52 UTC, StealthTech commented on components/Header/Header.js
> +        const avtor = document.createElement('div');
author

2022-12-15 22:52 UTC, StealthTech commented on components/RecipeCard/RecipeCard.css
> +    font-family: 'Cormorant Garamond', serif;
Используешь кастомные шрифты без их подключения и фолбека — не надо так

2022-12-15 22:52 UTC, StealthTech commented on main.css
> +    font-family: 'Roboto',sans-serif;
Пробел, кастомный шрифт без подключения и фолбека

2022-12-15 22:52 UTC, StealthTech commented on components/Header/Header.css
> +color: rgb(0, 0, 0);
Не исправлено по коду pull request

2022-12-15 23:04 UTC, Kuzy53 commented on components/DescriptionSiteEda/DescriptionSiteEda.css
> +    justify-content: center !important;
блин((

2022-12-18 15:45 UTC, StealthTech approved these changes

2022-12-18 15:47 UTC, merged

2022-12-18 15:48 UTC, StealthTech commented
Домашнее задание №2 засчитано с понижением балла за просроченный дедлайн (-1 балл)